# module téléinformation client
# rene-d 2020

FROM debian:buster

RUN apt-get update \
&&  apt-get install -y gdb make cmake gcc g++ libgtest-dev vim wget curl bash gcovr cppcheck git \
&&  python3 python3-pip

RUN wget -nv -P /usr/local/include/nlohmann/ https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp

RUN apt-get install -y --no-install-recommends nodejs npm
RUN npm install -g html-minifier

RUN pip3 install platformio \
&&  platformio platform install --with-package framework-arduinoespressif8266 espressif8266 \
&&  platformio settings set enable_telemetry false \
&&  platformio settings set check_libraries_interval 0 \
&&  platformio settings set check_platformio_interval 0 \
&&  platformio settings set check_platforms_interval 0

RUN pip3 install click sseclient influxdb flask flask-cors pyyaml pyserial
