{
 "title": "Consommation électrique",
 "time": { "from": "now-15d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "tarif_hc_ttc", "label": "Tarif Heures Creuses TTC", "query": "0.131988" },
   { "name": "tarif_hp_ttc", "label": "Tarif Heures Pleines TTC", "query": "0.170988" }
  ]
 },
 "panels": [
  {
   "title": "Consommation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "conso",
     "query": "SELECT derivative(mean(HCHP),3600s) as heures_pleines, derivative(mean(HCHC),3600s) as heures_creuses FROM conso WHERE $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "code", "operator": "=", "value": "HCHC" }
     ]
    }
   ]
  },
  {
   "title": "Coût",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "currencyEUR", "label": "€/h" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (derivative(mean(HCHP),1h) * $tarif_hp_ttc/1000  + derivative(mean(HCHC),1h) * $tarif_hc_ttc/1000) FROM conso WHERE $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(IINST),mean(IINST),min(IINST) FROM conso WHERE $timeFilter group by time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(PAPP),mean(PAPP),min(PAPP) FROM conso WHERE $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index courant Heures Pleines",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT last(HCHP) FROM conso  WHERE time > now() - 1h",
     "select": [
      [
       { "params": [ "HPHP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index courant  Heures Creuses",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(HCHC) FROM conso WHERE time > now() - 1h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissante apparente courante",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "format": "voltamp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(PAPP) FROM conso WHERE time > now() - 1h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}